In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)


[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [2]:
cal = A.sum(axis=0)

print(cal)


[ 59.  239.  155.4  76.9]


In [3]:
percentage = 100 * A/cal.reshape(1, 4)

print(percentage)


[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [5]:
a = np.random.rand(3, 3)

b = np.random.rand(3, 1)

c = a * b

print(c)
print(c.shape)


[[0.12264437 0.01042179 0.19394664]
 [0.20960492 0.12740032 0.28059678]
 [0.47475974 0.5405842  0.11868285]]
(3, 3)


In [10]:
a = np.random.rand(2, 3)
b = np.random.rand(2, 1)
c = a + b
print(c)
print(c.shape)



[[0.82426841 1.21831347 0.31129088]
 [1.53571414 0.90940952 1.38621561]]
(2, 3)


In [12]:
r = np.random.randn(4, 3)  # a.shape = (4, 3)
f = np.random.randn(3, 2)  # b.shape = (3, 2)
j = r*f
print(j)
print(j.shape)


ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [13]:
a = np.random.randn(12288, 150)  # a.shape = (12288, 150)
b = np.random.randn(150, 45)  # b.shape = (150, 45)
c = np.dot(a, b)
print(c)
print(c.shape)


[[-17.69781408  13.55320111  -8.44702635 ...  -0.86066915 -22.19989824
  -13.67904581]
 [ -3.66575232  -8.50309337  10.48884978 ...   9.88610505   5.31798044
   12.59220377]
 [  2.69649664   3.28109339  24.9969505  ...  19.8196536   11.4968698
   21.62135465]
 ...
 [ 13.43001465  -3.56837651 -11.46164641 ...  22.03826033  -1.97607961
   20.56674279]
 [ -0.8975743    8.86490323 -13.81177952 ...   5.97555394  17.12971166
   16.44907424]
 [ 13.70304743  12.90908119  -0.82918634 ...   3.62520013 -15.67762143
   16.38418745]]
(12288, 45)


In [14]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)
print(c.shape)


[[-2.61587801 -1.27243932  1.04809409]
 [-0.71351691  0.56957385 -0.1088449 ]
 [ 0.32340964 -0.05309494 -0.03682482]]
(3, 3)


In [16]:
# a.shape = (3,4)
# b.shape = (4,1)

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
    
print(c)

print(c.shape)


IndexError: index 3 is out of bounds for axis 0 with size 3